### ISSUE TITLE
Decide on format for MIxS URIs - unique IDs

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs-rdf#5]
Once namespace issue #2  is resolved, we need to decide if the unique part of each identifier should be an opaque string or meaningful, i.e.., should we use URIs like

`https://w3id.org/gensc.org/terms/MIXS_000001`
or
`https://w3id.org/gensc.org/terms/MIXS_depth`?

Should the prefix be MIXS, MIxS, or mixs?

**Comment by jdeck88** [comment]
I see the opaque identifiers as benefitting terms that have some kind of built-in logical entailments... However, since these URLs are pointing exclusively to data properties i think using transparent IDs would be fine here, and we get the added benefit of broader adoption and direct use of these URLs by the community... i think this is something that has helped Darwin Core get broader adoption and recognition.

**Comment by ramonawalls** [comment]
We discussed this at the CIG call today, and decided that it was best to use opaque identifiers. We can still main a mapping to term labels, so people don't have to look at the URIs in, e.g., spreadsheets.
